version: '3'

services:
  app1:
    image: world_hello
    ports:
      - "5001:5000"
    depends_on:
      - redis

  app2:
    image: world_hello
    ports:
      - "5002:5000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

