version: '3'

services:
  app1:
    image: world_hello
    ports:
      - "5001:5000"
    restart: always
    networks:
      - app-network
    depends_on:
      - redis

  app2:
    image: world_hello
    ports:
      - "5002:5000"
    restart: always
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  load_balancer:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

networks:
  app-network:
      driver: bridge


