version: '3'

services:
  app1:
    image: world_hello
    ports:
      - "5001:5000"
    depends_on:
      - redis

  app2:
    image: world_hello
    ports:
      - "5002:5000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  lb:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
